Verduleria/Controllers/VerduleriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Verduleria.Models;

namespace Verduleria.Controllers
{
    public class VerduleriaController : Controller
    {
        public async Task<IActionResult> Index()
        {
            List<Producto> productoList = new List<Producto>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7024/api/Producto"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    productoList = JsonConvert.DeserializeObject<List<Producto>>(apiResponse);
                }
            }

            List<Promocion> promocionList = new List<Promocion>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7024/api/Promocion"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    promocionList = JsonConvert.DeserializeObject<List<Promocion>>(apiResponse);
                }
            }

            Carrito carrito = new Carrito();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7024/api/Carrito/" + 1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    carrito = JsonConvert.DeserializeObject<Carrito>(apiResponse);
                }
            }

            var total = 0;
            if(carrito.DetalleCarrito != null)
            {
                foreach (DetalleCarrito detalle in carrito.DetalleCarrito)
                {
                    total += (int)detalle.Costo;
                }
                ViewData["DetalleCarrito"] = carrito.DetalleCarrito;
            }
            else
            {
                ViewData["DetalleCarrito"] = new List<DetalleCarrito>();
            }

            ViewData["Productos"] = productoList;
            ViewData["Promociones"] = promocionList;
            ViewData["TotalCarrito"] = total;
            return View();
        }

        public async Task<IActionResult> Checkout()
        {
            Carrito carrito = new Carrito();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7024/api/Carrito/" + 1))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    carrito = JsonConvert.DeserializeObject<Carrito>(apiResponse);
                }
            }

            var total = 0;
            if(carrito.DetalleCarrito != null)
            {
                foreach (DetalleCarrito detalle in carrito.DetalleCarrito)
                {
                    total += (int)detalle.Costo;
                }
            }
            else
            {
                carrito = new Carrito();
                carrito.DetalleCarrito = new List<DetalleCarrito>();
            }
            ViewData["TotalCarrito"] = total;

            return View(carrito);
        }

        public async Task<IActionResult> PostCarrito(string IdProducto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync("https://localhost:7024/api/Carrito?IdUsuario=" + 1 + "&IdProducto=" + IdProducto + "&cantidad=" + 1))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            if (response.IsSuccessStatusCode)
                            {
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> RestaCarrito(string IdProducto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync("https://localhost:7024/api/Carrito/RestaCarrito?IdUsuario=" + 1 + "&IdProducto=" + IdProducto + "&cantidad=" + 1))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            if (response.IsSuccessStatusCode)
                            {
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> CompraPromocion(string IdPromocion)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync("https://localhost:7024/api/Promocion/CompraPromocion?IdPromocion=" + IdPromocion + "&IdUsuario=1"))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            if (response.IsSuccessStatusCode)
                            {
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
                return View();

            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Compra()
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var httpClient = new HttpClient())
                    {
                        using (var response = await httpClient.GetAsync("https://localhost:7024/api/Compra?IdUsuario=" + 1))
                        {
                            string apiResponse = await response.Content.ReadAsStringAsync();
                            if (response.IsSuccessStatusCode)
                            {
                                return RedirectToAction(nameof(Index));
                            }
                        }
                    }
                }
                return RedirectToAction(nameof(Checkout));

            }
            catch
            {
                return RedirectToAction(nameof(Checkout));
            }
        }
    }
}

Verduleria/Views/Shared/Blog.cshtml
@model IEnumerable<Verduleria.Models.Promocion>


<div id="blog" class="container-fluid bg-dark text-light py-5 text-center wow fadeIn">
    <h2 class="section-title py-5">Promociones</h2>
    <div class="tab-content" id="pills-tabContent">
        @if (Model.Count() > 0){
            <div class="tab-pane fade show active" id="foods" role="tabpanel" aria-labelledby="pills-home-tab">
                <ul class="carousel">
                    @foreach (var promocion in ViewData["Promociones"] as IEnumerable<Verduleria.Models.Promocion>)
                    {
                        <li class="carousel-li col-md-6">
                            <div class="card bg-transparent border my-3 my-md-0">
                                <img src="~/assets/imgs/banano.jpg" alt="template by DevCRID http://www.devcrud.com/" class="rounded-0 card-img-top mg-responsive">
                                <div class="card-body">
                                    <h2 class="text-center mb-4"><a href="#" class="badge badge-primary">@Html.DisplayFor(modelItem => promocion.Nombre)</a></h2>
                                    <h5>
                                        @Html.DisplayFor(modelItem => promocion.Descripcion)
                                    </h5>
                                    <a asp-action="CompraPromocion" asp-controller="Verduleria" asp-route-IdPromocion="@promocion.Id" class="button button-cart w-100" style="height: 30px; display: flex; align-items: center; justify-content: center;">
                                        Comprar
                                    </a>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        }else{
            <div class="w-100 text-center no-disponible">
                <p>De momento no hay promociones disponibles</p>
            </div>
        }
    </div>
</div>

Verduleria/Views/Shared/Contact.cshtml
<div id="contact" class="container-fluid bg-dark text-light border-top wow fadeIn">
    <div class="row">
        <div class="col-md-6 px-0">
            <div id="map" style="width: 100%; height: 100%; min-height: 400px"></div>
        </div>
        <div class="col-md-6 px-5 has-height-lg middle-items">
            <h3>¡Visitenos!</h3>
            <div class="text-muted">
                <p><span class="ti-location-pin pr-3"></span>Avenida Central, entre Calle 5 y 7, San José Centro, Costa Rica.</p>
                <p><span class="ti-support pr-3"></span>(+506) 1234-5678</p>
            </div>
        </div>
    </div>
</div>

<!-- page footer  -->
    <div class="container-fluid bg-dark text-light has-height-md middle-items border-top text-center wow fadeIn">
        <div class="row">
            <div class="col-sm-4">
                <h3>EMAIL</h3>
                <P class="text-muted">verduleria@gmail.com</P>
            </div>
            <div class="col-sm-4">
                <h3>LLAMENOS</h3>
                <P class="text-muted">(+506) 1234-5678</P>
            </div>
            <div class="col-sm-4">
                <h3>ENCUENTRANOS</h3>
                <P class="text-muted">Avenida Central, entre Calle 5 y 7, San José Centro, Costa Rica.</P>
            </div>
        </div>
    </div>

Verduleria/Views/Shared/Gallary.cshtml
@model IEnumerable<Verduleria.Models.Producto>


<div id="gallary" class="text-center bg-dark text-light has-height-md middle-items wow fadeIn">
    <h2 class="section-title">NUESTROS PRODUCTOS</h2>
</div>
<div class="gallary row">
    @if(Model.Count() > 0){
        @foreach (var producto in ViewData["Productos"] as IEnumerable<Verduleria.Models.Producto>)
        {
            <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
                <img src="~/assets/imgs/gallary-1.jpg" alt="template by DevCRID http://www.devcrud.com/" class="gallary-img">
                <a class="gallary-overlay" asp-action="PostCarrito" asp-controller="Verduleria" asp-route-IdProducto="@producto.Id">
                    <h3>
                        @Html.DisplayFor(modelItem => producto.Nombre)
                    </h3>
                    <p>
                        @Html.DisplayFor(modelItem => producto.Descripcion)
                    </p>
                    <p>
                        ₡@Html.DisplayFor(modelItem => producto.Precio)
                    </p>
                    <i class="gallary-icon ti-plus"></i>
                </a>
            </div>
        }
    }else{
        <div class="w-100 text-center no-disponible">
            <p>De momento no hay productos disponibles</p>
        </div>
    }
</div>

Verduleria/Views/Shared/Reviews.cshtml
<div id="testmonial" class="container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items">
    <h2 class="section-title my-5 text-center">COMENTARIOS</h2>
    <div class="row mt-3 mb-5">
        <div class="col-md-4 my-3 my-md-0">
            <div class="testmonial-card">
                <h3 class="testmonial-title">Juan Carlos</h3>
                <div class="testmonial-body">
                    <p>Me encantó la variedad de productos frescos y locales que encontré en esta verdulería en San José. Los empleados fueron muy amables y me ayudaron a encontrar todo lo que necesitaba para mi ensalada de cena</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 my-3 my-md-0">
            <div class="testmonial-card">
                <h3 class="testmonial-title">Ana María</h3>
                <div class="testmonial-body">
                    <p>Esta verdulería es mi lugar favorito para comprar frutas y verduras frescas en San José. Siempre encuentro algo nuevo y delicioso para probar, y su selección de productos orgánicos es impresionante</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 my-3 my-md-0">
            <div class="testmonial-card">
                <h3 class="testmonial-title">Pedro José</h3>
                <div class="testmonial-body">
                    <p>Fui a esta verdulería por primera vez hoy y quedé impresionado con su atención al cliente. Me ayudaron a encontrar los ingredientes perfectos para mi receta y me dieron excelentes consejos sobre cómo prepararlos. Sin duda volveré</p>
                </div>
            </div>
        </div>
    </div>
</div>

Verduleria/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Jhon Doe</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a class="nav-item nav-link active" asp-action="Index"><i class="fa fa-tachometer-alt me-2"></i>Productos</a>
                    <a class="nav-item nav-link" asp-action="Promociones"><i class="fa fa-th me-2"></i>Promociones</a>
                    <a class="nav-item nav-link" asp-action="ProductoPromocion"><i class="fa fa-th me-2"></i>Producto en Promoción</a>
                    <a class="nav-item nav-link" asp-action="TipoProducto"><i class="fa fa-th me-2"></i>Tipo de Producto</a>
                    <a class="nav-item nav-link" asp-action="Usuario"><i class="fa fa-th me-2"></i>Usuario</a>
                    <a class="nav-item nav-link" asp-action="Rol"><i class="fa fa-th me-2"></i>Rol</a>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/assets/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">John Doe</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">Perfil</a>
                            <a href="#" class="dropdown-item">Cerrar Sesion</a>
                        </div>
                    </div>
                </div>
            </nav>
            @RenderBody()
        </div>
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src=""~/assets/lib/chart/chart.min.js"></script>
    <script src="~/assets/lib/easing/easing.min.js"></script>
    <script src="~/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/assets/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Verduleria/Views/Shared/_Layout.cshtml
@{
    var detalles = ViewData["DetalleCarrito"] as IEnumerable<Verduleria.Models.DetalleCarrito>;
    var cantidad = detalles.Count();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Verduleria</title>
    <!-- font icons -->
    <link rel="stylesheet" href="~/assets/vendors/themify-icons/css/themify-icons.css">

    <link rel="stylesheet" href="~/assets/vendors/animate/animate.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <!-- Bootstrap + FoodHut main styles -->
    <link rel="stylesheet" href="~/assets/css/foodhut.css">
    <link rel="stylesheet" href="~/css/carrito.css">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
    <header>
        <nav class="custom-navbar navbar navbar-expand-lg navbar-dark fixed-top" data-spy="affix" data-offset-top="10">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#home">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about">Sobre Nosotros</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#gallary">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#blog">Promociones</a>
                    </li>
                </ul>
                <a class="navbar-brand m-auto" href="#">
                    <img src="~/assets/imgs/logo.svg" class="brand-img" alt="">
                    <span class="brand-txt">Verduleria</span>
                </a>
                <ul class="navbar-nav second-nav">
                    <li class="nav-item cart">
                        <a id="cart" class="nav-link"><i class="fa fa-shopping-cart"></i>Carrito
                                <span class="badge-cart">@cantidad</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#testmonial">Comentarios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contactenos</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container-card">
            <div class="shopping-cart">
                <div class="shopping-cart-header">
                    <i class="fa fa-shopping-cart cart-icon"></i><span class="badge-cart">@cantidad</span>   
                    <div class="shopping-cart-total">
                        <span class="lighter-text">Total:</span>
                        <span class="main-color-text">$@ViewData["TotalCarrito"]</span>
                    </div>
                </div> <!--end shopping-cart-header -->

                <ul class="shopping-cart-items">
                    @foreach (var detalle in @detalles)
                    {
                        <li class="detalle">
                            <span class="item-name">@detalle.Producto.Nombre</span>
                            <span class="item-quantity">Cantidad: @detalle.CantidadProducto</span>
                            <span class="item-price">$@detalle.Costo</span>
                            @if(detalle.Editable){
                                <a asp-action="PostCarrito" asp-controller="Verduleria" asp-route-IdProducto="@detalle.Producto.Id">
                                    <i class="fa fa-regular fa-plus cart-icon"></i>
                                </a>
                                <a asp-action="RestaCarrito" asp-controller="Verduleria" asp-route-IdProducto="@detalle.Producto.Id">
                                    <i class="fa fa-solid fa-minus cart-icon"></i>
                                </a>
                            }
                        </li>
                    }
                </ul>

                <a asp-action="Checkout" asp-controller="Verduleria" class="button button-cart">Checkout</a>
            </div> <!--end shopping-cart -->
        </div> <!--end container -->
    </header>
    <div>
        @RenderBody()
    </div>

    <script src="~/assets/vendors/jquery/jquery-3.4.1.js"></script>
    <script src="~/assets/vendors/bootstrap/bootstrap.bundle.js"></script>

    <!-- bootstrap affix -->
    <script src="~/assets/vendors/bootstrap/bootstrap.affix.js"></script>

    <!-- wow.js -->
    <script src="~/assets/vendors/wow/wow.js"></script>

    <!-- google maps -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtme10pzgKSPeJVJrG1O3tjR6lk98o4w8&callback=initMap"></script>

    <!-- FoodHut js -->
    <script src="~/assets/js/foodhut.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/js/carrito.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Verduleria/Views/Shared/_LayoutCheckout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Verduleria</title>
    <link rel="stylesheet" href="~/css/checkout.css">
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/js/checkout.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>